#!/bin/bash

# Running this looks at all the files in this directory and makes symlinks to
#  all of them. The symlinks are of the form ~/.<name> where <name> is the name
#  of the file in this directory. In words, it adds a dot to the beginning
#  and puts it in the home directory. If there's already a file there, it is
#  renamed with a .old extension and a warning is printed.

thisdir=$(basename "$PWD")
while IFS= read -d $'\0' -r file ; do
    filename=$(basename ${file})
    newfile=~/."$filename"
    #printf 'File found: %s New name will be %s \n' "$file" "$newname"
    if [[ -a $newfile ]]; then
        echo '`'"$newfile' already exists. Moving to $newfile.old"
        mv -i "$newfile" "$newfile.old"
    fi
    echo ln -s "$thisdir/$filename" "$newfile"
    ln -s "$thisdir/$filename" "$newfile"
done < <(find . -maxdepth 1 -mindepth 1 ! \( -name ".git" -o -name "etc" -o -name "getdots" -o -name "setdots" \) -print0 )
