" All system-wide defaults are set in $VIMRUNTIME/debian.vim and sourced by
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
" adam > debian
" runtime! debian.vim

set nocompatible
set backspace=indent,eol,start
set ruler

"###############################################
"########### Adam's copied stuff ##############
"###############################################

" Tabs become spaces
set tabstop=8
set shiftwidth=4
set expandtab
set softtabstop=4

" Search better
set ignorecase
set smartcase
set incsearch

set mouse=a

set showcmd

syntax enable

autocmd FileType make setlocal noexpandtab " Don't turn tabs into spaces

set autowrite

set relativenumber
set numberwidth=2

" Mark lines that wrap around
set showbreak=->

"set shortmess+=I

colorscheme slate
" Uhh... if I don't set to light first, the comments are white which sucks
se bg=light
se bg=dark

map <C-Tab> gt
map <C-S-Tab> gT
imap <C-Tab> gt
imap <C-S-Tab> gT

" Don't let the cursor get to close to top or bottom of page
set scrolloff=5
" Completion for command mode commands

set wildmode=longest,list,full
set wildmenu

" Source a global configuration file if available
"if filereadable("/etc/vim/vimrc.local")
"  source /etc/vim/vimrc.local
"endif

autocmd FileType txt,markdown setlocal spell " Spellcheck
" Match < to > like parentheses
set matchpairs+=<:>

" Make new splits open up below the main window
set splitbelow

" Make extra whitespace at end of line display, show tabs specially, and
" give a marker when things have gone of screen
set list
set listchars=trail:-,tab:>-,precedes:#,extends:#

set nojoinspaces
